In [1]:
import sparse
import torch

from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
from sb3_contrib.common.wrappers import ActionMasker
from sb3_contrib.ppo_mask import MaskablePPO

from src.environment.env_place_pair import GraphSeriesEnvPlacePair
from src.models.ppo_policy import CustomPPOPolicy
from src.utils.callback import CustomTensorboardCallback
from trainer import Trainer

In [2]:
# environment
import yaml

with open('config.yaml', "r") as file:
    config = yaml.safe_load(file)

a = sparse.load_npz('data/cuccaroadder_q8.npz')
a = a[:3]
#circuit_config = {'circuit': a}


def make_env():
    env = GraphSeriesEnvPlacePair(circuit_config=config['circuit'], action_type=config['action_type'], weights_reward=config['weights_reward'])
    print(env.circuit.todense())
    env = ActionMasker(env, lambda e: e.env_mask())
    #env = Monitor(env)
    return env


env = DummyVecEnv([make_env])
print(env.envs[0])

[[[0 0 0 0]
  [0 0 1 0]
  [0 1 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 1 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 1 0]]]
<ActionMasker<GraphSeriesEnvPlacePair instance>>


In [3]:
env.envs[0].step(0)

nlcomm computed in take action [0. 0.]
self.weights_reward[nonlocal] <class 'int'>
nl_com <class 'numpy.ndarray'>
self.weights_reward[intervention] <class 'int'>
intervention <class 'bool'>
reward [-20. -20.]
allocation after action
[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
STEP RETURN DEBUG
Observation keys and shapes:
  old_allocation: type=<class 'numpy.ndarray'>, shape=(4, 2)
  new_allocation: type=<class 'numpy.ndarray'>, shape=(4, 2)
  interactions: type=<class 'numpy.ndarray'>, shape=(4, 4)
  lookaheads: type=<class 'numpy.ndarray'>, shape=(4,)
  n_qbits: type=<class 'numpy.ndarray'>, shape=(1,)
  core_capacities: type=<class 'numpy.ndarray'>, shape=(2,)
  flag: type=<class 'numpy.ndarray'>, shape=(4, 1)
Reward: [-20. -20.] <class 'numpy.ndarray'>
Done: False <class 'bool'>
Truncated: False <class 'bool'>
Info: {}


({'old_allocation': array([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]),
  'new_allocation': array([[1., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]),
  'interactions': array([[0, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 1, 0, 0],
         [0, 0, 0, 0]]),
  'lookaheads': array([0., 0., 1., 0.]),
  'n_qbits': array([4]),
  'core_capacities': array([3, 4]),
  'flag': array([[0.],
         [1.],
         [0.],
         [0.]])},
 array([-20., -20.]),
 False,
 False,
 {})